### ISSUE TITLE
Class 'ElcoBvG\Opcache\Model' not found

### ISSUE THREAD

**Issue by ITwrx** [elcobvg/laravel-opcache#11]
hi,
very excited to use this, but when i do this:

`//use Illuminate\Database\Eloquent\Model;`
`use ElcoBvG\Opcache\Model;`

i get:

`Class 'ElcoBvG\Opcache\Model' not found`

thanks

**Comment by elcobvg** [comment]
Apologies, I made a typo in the docs: it should be `ElcoBvg\Opcache\Model` (notice the lower case **g** in `ElcoBvg`)

**Comment by ITwrx** [comment]
great, thanks. knew it had to be something simple.
