### ISSUE TITLE
Laravel 7.x compatibility

### ISSUE THREAD

**Issue by ruskiyos** [elcobvg/laravel-opcache#16]
As of Laravel 5.8, str helper classes are deprecated.

https://github.com/laravel/framework/pull/26898

The constructor still uses `str_slug`.

```php
$this->prefix = str_slug($prefix ?: config('app.name', 'opcache'), '-');
```

Can this please be updated to use `Str::slug` instead?

**Comment by elcobvg** [comment]
Good catch, thanks! Fixed now.
