### ISSUE TITLE
WhiteFile() receiving float instead int

### ISSUE THREAD

**Issue by jonathangoncalves** [elcobvg/laravel-opcache#9]
I'm running my application with opcache, and give this error:

> Type error: Argument 2 passed to ElcoBvg\Opcache\Store::writeFile() must be of the type integer, float given, called in \vendor\elcobvg\laravel-opcache\src\Store.php on line 104

The fix is just cast the $expiration before send, but I don't know what is the real problem, if it's mine...

What's the deal?

**Comment by elcobvg** [comment]
Yeah, shouldn't happen obviously. As soon as I find some time, I'll look into this.

**Comment by elcobvg** [comment]
Can you provide a little bit more context about how/when this happened in your app?
Other than forcing the issue by hard coding an artificial test case, I haven't been able to reproduce your error...
